import 'package:flutter/foundation.dart';

final ValueNotifier<String> localeNotifier = ValueNotifier<String>('uz');

class AppLocalizations {
  static const Map<String, Map<String, String>> _translations = {
    'uz': {
      'welcome': 'Xush kelibsiz',
      'gifts': 'Sovg\'alar',
      'search_gifts': 'Sovg\'alarni qidirish...',
      'your_points': 'Sizning ballaringiz',
      'all': 'Barchasi',
      'tech': 'Texnika',
      'clothes': 'Kiyimlar',
      'vouchers': 'Vaucherlar',
      'other': 'Boshqa',
      'settings': 'Sozlamalar',
      'edit_profile': 'Profilni tahrirlash',
      'pause_notif': 'Bildirishnomalarni to\'xtatish',
      'general_settings': 'Umumiy sozlamalar',
      'dark_mode': 'Tungi rejim',
      'language': 'Til (Language)',
      'my_contact': 'Mening kontaktim',
      'faq': 'Ko\'p beriladigan savollar',
      'terms': 'Xizmat ko\'rsatish shartlari',
      'user_policy': 'Foydalanuvchi siyosati',
      'logout': 'Tizimdan chiqish',
      'full_name': 'To\'liq ism',
      'phone_number': 'Telefon raqam',
      'save_changes': 'O\'zgarishlarni saqlash',
      'delete_account': 'Hisobni o\'chirish',
      'my_card': 'Mening Kartam',
      'recent_activity': 'So\'nggi harakatlar',
      'choose_design': 'Karta dizaynini tanlang',
      'scanned_product': 'skanerlandi',
      'today': 'Bugun',
      'basic': 'Asosiy',
      'orange': 'Apelsin',
      'pink': 'Pushti',
      'black': 'Qora',
      'red': 'Qizil',
      'night': 'Tungi',
      'purple': 'Binafsha',
      'coming_soon': 'Tez kunda...',
      'product': 'Mahsulot',
      'faq_q1': 'Qanday qilib ball ishlashim mumkin?',
      'faq_a1': 'Asosiy ekrandagi skaner tugmasi orqali xarid qilingan mahsulot QR kodini skanerlang.',
      'faq_q2': 'Ballarni nimalarga ishlatish mumkin?',
      'faq_a2': 'Yig\'ilgan ballaringiz evaziga "Sovg\'alar" bo\'limidan vaucher, texnika yoki boshqa qimmatbaho sovg\'alarni xarid qilishingiz mumkin.',
      'faq_q3': 'Parolimni qanday tiklayman?',
      'faq_a3': 'Kirish ekranidagi "Parolni unutdingizmi?" tugmasini bosib, pochtangiz orqali tiklashingiz mumkin.',
      'policy_title': 'Foydalanuvchi siyosati',
      'policy_content': 'Ushbu ilovadan foydalanish orqali siz bizning shartlarimizga rozi bo\'lasiz. Sizning shaxsiy ma\'lumotlaringiz xavfsizligi kafolatlanadi. Loyiha qoidalari va bonus tizimidan faqat qoidalarga muvofiq foydalanish ruxsat etiladi.',
      'card_holder': 'Karta egasi',
      'current_balance': 'Joriy balans',
      'points': 'ball',
      'card_info': 'Ushbu karta Volt Loyalty dasturi foydalanuvchilariga tegishli. Agar uni topib olsangiz, iltimos kompaniyaga qaytaring yoki +998901234567 raqamiga qo\'ng\'iroq qiling.',
      'scanner': 'QR Skaner',
      'scanned_msg': 'Skanerlandi:',
    },
    'ru': {
      'welcome': 'Добро пожаловать',
      'gifts': 'Подарки',
      'search_gifts': 'Поиск подарков...',
      'your_points': 'Ваши баллы',
      'all': 'Все',
      'tech': 'Техника',
      'clothes': 'Одежда',
      'vouchers': 'Ваучеры',
      'other': 'Другое',
      'settings': 'Настройки',
      'edit_profile': 'Редактировать профиль',
      'pause_notif': 'Приостановить уведомления',
      'general_settings': 'Общие настройки',
      'dark_mode': 'Темный режим',
      'language': 'Язык (Language)',
      'my_contact': 'Мой контакт',
      'faq': 'Часто задаваемые вопросы',
      'terms': 'Условия обслуживания',
      'user_policy': 'Пользовательское соглашение',
      'logout': 'Выйти',
      'full_name': 'Полное имя',
      'phone_number': 'Номер телефона',
      'save_changes': 'Сохранить изменения',
      'delete_account': 'Удалить аккаунт',
      'my_card': 'Моя карта',
      'recent_activity': 'Последние действия',
      'choose_design': 'Выберите дизайн карты',
      'scanned_product': 'отсканирован',
      'today': 'Сегодня',
      'basic': 'Базовый',
      'orange': 'Оранжевый',
      'pink': 'Розовый',
      'black': 'Черный',
      'red': 'Красный',
      'night': 'Ночной',
      'purple': 'Фиолетовый',
      'coming_soon': 'Скоро...',
      'product': 'Товар',
      'faq_q1': 'Как я могу заработать баллы?',
      'faq_a1': 'Сканируйте QR-код купленного товара с помощью кнопки сканера на главном экране.',
      'faq_q2': 'На что можно потратить баллы?',
      'faq_a2': 'Накопленные баллы можно обменять на ваучеры, технику или другие подарки в разделе "Подарки".',
      'faq_q3': 'Как восстановить пароль?',
      'faq_a3': 'Нажмите "Забыли пароль?" на экране входа и восстановите через почту.',
      'policy_title': 'Пользовательское соглашение',
      'policy_content': 'Используя это приложение, вы соглашаетесь с нашими условиями. Безопасность ваших личных данных гарантируется. Система бонусов может использоваться только в соответствии с правилами проекта.',
      'card_holder': 'Владелец карты',
      'current_balance': 'Текущий баланс',
      'points': 'баллов',
      'card_info': 'Эта карта принадлежит пользователю программы Volt Loyalty. Если вы ее нашли, пожалуйста, верните в компанию или позвоните по номеру +998901234567.',
      'scanner': 'QR Сканер',
      'scanned_msg': 'Отсканировано:',
    },
    'en': {
      'welcome': 'Welcome',
      'gifts': 'Gifts',
      'search_gifts': 'Search gifts...',
      'your_points': 'Your points',
      'all': 'All',
      'tech': 'Tech',
      'clothes': 'Clothes',
      'vouchers': 'Vouchers',
      'other': 'Other',
      'settings': 'Settings',
      'edit_profile': 'Edit Profile',
      'pause_notif': 'Pause notifications',
      'general_settings': 'General settings',
      'dark_mode': 'Dark mode',
      'language': 'Language',
      'my_contact': 'My Contact',
      'faq': 'FAQ',
      'terms': 'Terms of service',
      'user_policy': 'User policy',
      'logout': 'Log Out',
      'full_name': 'Full name',
      'phone_number': 'Phone number',
      'save_changes': 'Save Changes',
      'delete_account': 'Delete Account',
      'my_card': 'My Card',
      'recent_activity': 'Recent activity',
      'choose_design': 'Choose card design',
      'scanned_product': 'scanned',
      'today': 'Today',
      'basic': 'Basic',
      'orange': 'Orange',
      'pink': 'Pink',
      'black': 'Black',
      'red': 'Red',
      'night': 'Night',
      'purple': 'Purple',
      'coming_soon': 'Coming soon...',
      'product': 'Product',
      'faq_q1': 'How can I earn points?',
      'faq_a1': 'Scan the QR code of a purchased product using the scanner button on the home screen.',
      'faq_q2': 'What can I use points for?',
      'faq_a2': 'You can exchange your accumulated points for vouchers, electronics, or other gifts in the "Gifts" section.',
      'faq_q3': 'How do I reset my password?',
      'faq_a3': 'Click "Forgot password?" on the login screen and reset it via email.',
      'policy_title': 'User Policy',
      'policy_content': 'By using this application, you agree to our terms and conditions. The security of your personal data is guaranteed. The bonus system may only be used in accordance with the project rules.',
      'card_holder': 'Card Holder name',
      'current_balance': 'Current Balance',
      'points': 'points',
      'card_info': 'This card belongs to a user of the Volt Loyalty program. If you find it, please return it to the company or call +998901234567.',
      'scanner': 'QR Scanner',
      'scanned_msg': 'Scanned:',
    }
  };

  static String get(String key) {
    return _translations[localeNotifier.value]?[key] ?? key;
  }
}

extension LocalizationHelper on String {
  String get tr {
    return AppLocalizations.get(this);
  }
}
