import 'package:flutter/foundation.dart';

final ValueNotifier<String> localeNotifier = ValueNotifier<String>('uz');

class AppLocalizations {
  static const Map<String, Map<String, String>> _translations = {
    'uz': {
      'welcome': 'Xush kelibsiz',
      'gifts': 'Sovg\'alar',
      'search_gifts': 'Sovg\'alarni qidirish...',
      'your_points': 'Sizning ballaringiz',
      'all': 'Barchasi',
      'tech': 'Texnika',
      'clothes': 'Kiyimlar',
      'vouchers': 'Vaucherlar',
      'other': 'Boshqa',
      'settings': 'Sozlamalar',
      'edit_profile': 'Profilni tahrirlash',
      'pause_notif': 'Bildirishnomalarni to\'xtatish',
      'general_settings': 'Umumiy sozlamalar',
      'points_history': 'Ballar tarixi',
      'dark_mode': 'Tungi rejim',
      'language': 'Til (Language)',
      'my_contact': 'Mening kontaktim',
      'contact_us': 'Biz bilan bog\'lanish',
      'faq': 'Ko\'p beriladigan savollar',
      'terms': 'Xizmat ko\'rsatish shartlari',
      'user_policy': 'Foydalanuvchi siyosati',
      'logout': 'Tizimdan chiqish',
      'full_name': 'To\'liq ism',
      'phone_number': 'Telefon raqam',
      'save_changes': 'O\'zgarishlarni saqlash',
      'delete_account': 'Hisobni o\'chirish',
      'my_card': 'Mening Kartam',
      'recent_activity': 'So\'nggi harakatlar',
      'choose_design': 'Karta dizaynini tanlang',
      'scanned_product': 'skanerlandi',
      'today': 'Bugun',
      'basic': 'Asosiy',
      'orange': 'Apelsin',
      'pink': 'Pushti',
      'black': 'Qora',
      'red': 'Qizil',
      'night': 'Tungi',
      'purple': 'Binafsha',
      'coming_soon': 'Tez kunda...',
      'product': 'Mahsulot',
      'faq_q1': 'Qanday qilib ball ishlashim mumkin?',
      'faq_a1': 'Asosiy ekrandagi skaner tugmasi orqali xarid qilingan mahsulot QR kodini skanerlang.',
      'faq_q2': 'Ballarni nimalarga ishlatish mumkin?',
      'faq_a2': 'Yig\'ilgan ballaringiz evaziga "Sovg\'alar" bo\'limidan vaucher, texnika yoki boshqa qimmatbaho sovg\'alarni xarid qilishingiz mumkin.',
      'faq_q3': 'Parolimni qanday tiklayman?',
      'faq_a3': 'Kirish ekranidagi "Parolni unutdingizmi?" tugmasini bosib, pochtangiz orqali tiklashingiz mumkin.',
      'policy_title': 'Foydalanuvchi siyosati',
      'policy_content': 'Ushbu ilovadan foydalanish orqali siz bizning shartlarimizga rozi bo\'lasiz. Sizning shaxsiy ma\'lumotlaringiz xavfsizligi kafolatlanadi. Loyiha qoidalari va bonus tizimidan faqat qoidalarga muvofiq foydalanish ruxsat etiladi.',
      'card_holder': 'Karta egasi',
      'current_balance': 'Joriy balans',
      'points': 'ball',
      'card_info': 'Ushbu karta Volt Loyalty dasturi foydalanuvchilariga tegishli. Agar uni topib olsangiz, iltimos kompaniyaga qaytaring yoki +998901234567 raqamiga qo\'ng\'iroq qiling.',
      'scanner': 'QR Skaner',
      'login_title': 'Tizimga kirish',
      'enter_phone_password': 'Telefon raqam va parolni kiriting',
      'login_btn': 'Kirish',
      'forgot_password': 'Parolni unutdingizmi?',
      'password_label': 'Parol',
      'check_via_qr': 'QR orqali tekshirish',
      'forgot_password_title': 'Parolni tiklash',
      'enter_new_password': 'Yangi parolni kiriting',
      'forgot_password_desc': 'Parolingizni tiklash uchun telefon raqamingiz va yangi parolingizni kiriting. SMS orqali kod yuboriladi.',
      'new_password': 'Yangi parol',
      'confirm_new_password': 'Yangi parolni tasdiqlang',
      'send_code': 'Kodni yuborish',
      'passwords_do_not_match': 'Parollar mos kelmadi',
      'cant_open_phone': 'Telefon raqamni ochib bo\'lmadi',
      'application_under_review': 'Arizangiz hali ko\'rib chiqilmoqda',
      'pending_approval_title': 'Arizangiz ko\'rib chiqilmoqda',
      'pending_approval_desc': 'Ro\'yxatdan o\'tganingiz uchun rahmat! Ma\'muriyat profilingizni tasdiqlaganidan so\'ng tizimdan foydalanishingiz mumkin bo\'ladi.',
      'contact_admin_desc': 'Tasdiqlashni tezlashtirish uchun Admin bilan bog\'lanishingiz mumkin:',
      'no_admin_phones': 'Hozircha admin raqamlari mavjud emas',
      'check_status_btn': 'Holatni tekshirish',
      'no_account': 'Akkauntingiz yo\'qmi? ',
      'register_btn': 'Ro\'yxatdan o\'tish',
      'first_name': 'Ism',
      'last_name': 'Familiya',
      'age': 'Yoshingiz',
      'phone': 'Telefon raqam',
      'select_region': 'Viloyatni tanlang',
      'district': 'Tuman (Yashash manzili)',
      'create_password': 'Parol o\'ylab toping',
      'i_agree': 'Men',
      'privacy_policy': 'Maxfiylik siyosati',
      'new_master_profile': 'Yangi Usta profili',
      'enter_correct_data': 'Barcha ma\'lumotlarni to\'g\'ri kiriting',
      'fill_all_fields': 'Barcha maydonlarni to\'ldiring!',
      'password_min_6': 'Parol kamida 6 ta belgidan iborat bo\'lishi kerak',
      'agree_policy': 'Iltimos, Maxfiylik siyosatiga rozi bo\'ling!',
      'age_min_15': 'Yoshingiz kamida 15 bo\'lishi kerak',
      'scanned_msg': 'Skanerlandi:',
      'great': 'Ajoyib!',
      'price': 'Narxi',
      'scanned_times': 'Skanerlangan',
      'times': 'marta',
      'close': 'Yopish',
      'login': 'Tizimga kirish',
      'error': 'Xatolik',
      'send': 'Jo\'natish',
      'manual_entry': 'Qo\'lda kiritish',
      'enter_qr_number': 'QR kod tagidagi raqamni yozing',
      'cancel': 'Bekor qilish',
      'confirm': 'Tasdiqlash',
      'leave_complaint': 'Shikoyat qoldirish',
      'submit': 'Yuborish',
      'verify_code': 'Kodni tasdiqlash',
      'enter_6_digit': '6 xonali kodni kiriting',
      'code_resent': 'Kod qayta yuborildi',
      'reset_password': 'Parolni tiklash',
      'passwords_mismatch': 'Parollar mos kelmadi',
      'registration': 'Ro\'yxatdan o\'tish',
      'application_pending': 'Arizangiz hali ko\'rib chiqilmoqda',
      'no_admin_numbers': 'Hozircha admin raqamlari mavjud emas',
      'check_status': 'Holatni tekshirish',
      'logout_account': 'Hisobdan chiqish',
      'no_activity': 'Hozircha faollik yo\'q',
      'image_uploaded': 'Rasm yuklandi',
      'profile_updated': 'Profil yangilandi',
      'delete_account_confirm': 'Haqiqatan ham hisobingizni o\'chirmoqchimisiz? Bu amalni ortga qaytarib bo\'lmaydi.',
      'status': 'Holati',
      'status_active': 'Faol (Yangi)',
      'status_inactive': 'Ishlatilgan',
      'attention': 'Diqqat',
      'scanned_by_self': 'Siz buni oldin skannerlagansiz!',
      'scanned_by_other': 'Bu QR kod oldin faollashtirilgan!',
      'send_complaint': 'Shikoyat jo\'natish',
      'understood': 'Tushunarli',
      'congratulations': 'Tabriklaymiz!',
      'loading': 'Yuklanmoqda...',
      'login_to_add_points': 'Ushbu ballarni hisobingizga qo\'shish uchun tizimga kiring!',
      'complaint_sent': 'Shikoyat yuborildi',
      'camera_error': 'Kamerani ishga tushirib bo\'lmadi.\nIlovani qayta oching.',
      'product_activated': 'Mahsulot muvaffaqiyatli faollashtirildi!',
      'for_product_activated': 'uchun muvaffaqiyatli faollashtirildi.',
    },
    'ru': {
      'welcome': 'Добро пожаловать',
      'gifts': 'Подарки',
      'search_gifts': 'Поиск подарков...',
      'your_points': 'Ваши баллы',
      'all': 'Все',
      'tech': 'Техника',
      'clothes': 'Одежда',
      'vouchers': 'Ваучеры',
      'other': 'Другое',
      'settings': 'Настройки',
      'edit_profile': 'Редактировать профиль',
      'pause_notif': 'Приостановить уведомления',
      'general_settings': 'Общие настройки',
      'points_history': 'История баллов',
      'dark_mode': 'Темный режим',
      'language': 'Язык (Language)',
      'my_contact': 'Мой контакт',
      'contact_us': 'Связаться с нами',
      'faq': 'Часто задаваемые вопросы',
      'terms': 'Условия обслуживания',
      'user_policy': 'Пользовательское соглашение',
      'logout': 'Выйти',
      'full_name': 'Полное имя',
      'phone_number': 'Номер телефона',
      'save_changes': 'Сохранить изменения',
      'delete_account': 'Удалить аккаунт',
      'my_card': 'Моя карта',
      'recent_activity': 'Последние действия',
      'choose_design': 'Выберите дизайн карты',
      'scanned_product': 'отсканирован',
      'today': 'Сегодня',
      'basic': 'Базовый',
      'orange': 'Оранжевый',
      'pink': 'Розовый',
      'black': 'Черный',
      'red': 'Красный',
      'night': 'Ночной',
      'purple': 'Фиолетовый',
      'coming_soon': 'Скоро...',
      'product': 'Товар',
      'faq_q1': 'Как я могу заработать баллы?',
      'faq_a1': 'Сканируйте QR-код купленного товара с помощью кнопки сканера на главном экране.',
      'faq_q2': 'На что можно потратить баллы?',
      'faq_a2': 'Накопленные баллы можно обменять на ваучеры, технику или другие подарки в разделе "Подарки".',
      'faq_q3': 'Как восстановить пароль?',
      'faq_a3': 'Нажмите "Забыли пароль?" на экране входа и восстановите через почту.',
      'policy_title': 'Пользовательское соглашение',
      'policy_content': 'Используя это приложение, вы соглашаетесь с нашими условиями. Безопасность ваших личных данных гарантируется. Система бонусов может использоваться только в соответствии с правилами проекта.',
      'card_holder': 'Владелец карты',
      'current_balance': 'Текущий баланс',
      'points': 'баллов',
      'card_info': 'Эта карта принадлежит пользователю программы Volt Loyalty. Если вы ее нашли, пожалуйста, верните в компанию или позвоните по номеру +998901234567.',
      'scanner': 'QR Сканер',
      'login_title': 'Вход в систему',
      'enter_phone_password': 'Введите номер телефона и пароль',
      'login_btn': 'Войти',
      'forgot_password': 'Забыли пароль?',
      'password_label': 'Пароль',
      'check_via_qr': 'Проверка через QR',
      'forgot_password_title': 'Сброс пароля',
      'enter_new_password': 'Введите новый пароль',
      'forgot_password_desc': 'Для сброса пароля введите свой номер телефона и новый пароль. Код будет отправлен по SMS.',
      'new_password': 'Новый пароль',
      'confirm_new_password': 'Подтвердите новый пароль',
      'send_code': 'Отправить код',
      'passwords_do_not_match': 'Пароли не совпадают',
      'cant_open_phone': 'Не удалось открыть номер телефона',
      'application_under_review': 'Ваша заявка все еще рассматривается',
      'pending_approval_title': 'Ваша заявка рассматривается',
      'pending_approval_desc': 'Спасибо за регистрацию! После того как администрация подтвердит ваш профиль, вы сможете пользоваться системой.',
      'contact_admin_desc': 'Чтобы ускорить подтверждение, вы можете связаться с администратором:',
      'no_admin_phones': 'В настоящее время номеров администраторов нет',
      'check_status_btn': 'Проверить статус',
      'no_account': 'Нет аккаунта? ',
      'register_btn': 'Регистрация',
      'first_name': 'Имя',
      'last_name': 'Фамилия',
      'age': 'Возраст',
      'phone': 'Номер телефона',
      'select_region': 'Выберите регион',
      'district': 'Район (Место жительства)',
      'create_password': 'Придумайте пароль',
      'i_agree': 'Я согласен с',
      'privacy_policy': 'Политикой конфиденциальности',
      'new_master_profile': 'Новый профиль мастера',
      'enter_correct_data': 'Введите все данные правильно',
      'fill_all_fields': 'Заполните все поля!',
      'password_min_6': 'Пароль должен содержать минимум 6 символов',
      'agree_policy': 'Пожалуйста, согласитесь с Политикой конфиденциальности!',
      'age_min_15': 'Ваш возраст должен быть не менее 15 лет',
      'scanned_msg': 'Отсканировано:',
      'great': 'Отлично!',
      'price': 'Цена',
      'scanned_times': 'Отсканировано',
      'times': 'раз(а)',
      'close': 'Закрыть',
      'login': 'Войти',
      'error': 'Ошибка',
      'send': 'Отправить',
      'manual_entry': 'Ввод вручную',
      'enter_qr_number': 'Введите номер под QR-кодом',
      'cancel': 'Отмена',
      'confirm': 'Подтвердить',
      'leave_complaint': 'Оставить жалобу',
      'submit': 'Отправить',
      'verify_code': 'Подтверждение кода',
      'enter_6_digit': 'Введите 6-значный код',
      'code_resent': 'Код отправлен повторно',
      'reset_password': 'Сброс пароля',
      'passwords_mismatch': 'Пароли не совпадают',
      'registration': 'Регистрация',
      'application_pending': 'Ваша заявка все еще рассматривается',
      'no_admin_numbers': 'Номера администраторов пока недоступны',
      'check_status': 'Проверить статус',
      'logout_account': 'Выйти из аккаунта',
      'no_activity': 'Пока нет активности',
      'image_uploaded': 'Изображение загружено',
      'profile_updated': 'Профиль обновлен',
      'delete_account_confirm': 'Вы действительно хотите удалить свой аккаунт? Это действие необратимо.',
      'status': 'Статус',
      'status_active': 'Активный (Новый)',
      'status_inactive': 'Использован',
      'attention': 'Внимание',
      'scanned_by_self': 'Вы уже сканировали это!',
      'scanned_by_other': 'Этот QR код уже был активирован!',
      'send_complaint': 'Отправить жалобу',
      'understood': 'Понятно',
      'congratulations': 'Поздравляем!',
      'loading': 'Загрузка...',
      'login_to_add_points': 'Войдите в систему, чтобы добавить эти баллы на свой счет!',
      'complaint_sent': 'Жалоба отправлена',
      'camera_error': 'Не удалось запустить камеру.\nПерезапустите приложение.',
      'product_activated': 'Товар успешно активирован!',
      'for_product_activated': 'успешно активирован.',
    },
    'en': {
      'welcome': 'Welcome',
      'gifts': 'Gifts',
      'search_gifts': 'Search gifts...',
      'your_points': 'Your points',
      'all': 'All',
      'tech': 'Tech',
      'clothes': 'Clothes',
      'vouchers': 'Vouchers',
      'other': 'Other',
      'settings': 'Settings',
      'edit_profile': 'Edit Profile',
      'pause_notif': 'Pause notifications',
      'general_settings': 'General settings',
      'points_history': 'Points history',
      'dark_mode': 'Dark mode',
      'language': 'Language',
      'my_contact': 'My Contact',
      'contact_us': 'Contact us',
      'faq': 'FAQ',
      'terms': 'Terms of service',
      'user_policy': 'User policy',
      'logout': 'Log Out',
      'full_name': 'Full name',
      'phone_number': 'Phone number',
      'save_changes': 'Save Changes',
      'delete_account': 'Delete Account',
      'my_card': 'My Card',
      'recent_activity': 'Recent activity',
      'choose_design': 'Choose card design',
      'scanned_product': 'scanned',
      'today': 'Today',
      'basic': 'Basic',
      'orange': 'Orange',
      'pink': 'Pink',
      'black': 'Black',
      'red': 'Red',
      'night': 'Night',
      'purple': 'Purple',
      'coming_soon': 'Coming soon...',
      'product': 'Product',
      'faq_q1': 'How can I earn points?',
      'faq_a1': 'Scan the QR code of a purchased product using the scanner button on the home screen.',
      'faq_q2': 'What can I use points for?',
      'faq_a2': 'You can exchange your accumulated points for vouchers, electronics, or other gifts in the "Gifts" section.',
      'faq_q3': 'How do I reset my password?',
      'faq_a3': 'Click "Forgot password?" on the login screen and reset it via email.',
      'policy_title': 'User Policy',
      'policy_content': 'By using this application, you agree to our terms and conditions. The security of your personal data is guaranteed. The bonus system may only be used in accordance with the project rules.',
      'card_holder': 'Card Holder name',
      'current_balance': 'Current Balance',
      'points': 'points',
      'card_info': 'This card belongs to a user of the Volt Loyalty program. If you find it, please return it to the company or call +998901234567.',
      'scanner': 'QR Scanner',
      'login_title': 'Login',
      'enter_phone_password': 'Enter phone number and password',
      'login_btn': 'Login',
      'forgot_password': 'Forgot password?',
      'password_label': 'Password',
      'check_via_qr': 'Check via QR',
      'forgot_password_title': 'Reset Password',
      'enter_new_password': 'Enter new password',
      'forgot_password_desc': 'To reset your password, enter your phone number and a new password. A code will be sent via SMS.',
      'new_password': 'New password',
      'confirm_new_password': 'Confirm new password',
      'send_code': 'Send code',
      'passwords_do_not_match': 'Passwords do not match',
      'cant_open_phone': 'Could not open phone number',
      'application_under_review': 'Your application is still under review',
      'pending_approval_title': 'Your application is under review',
      'pending_approval_desc': 'Thank you for registering! Once the administration approves your profile, you will be able to use the system.',
      'contact_admin_desc': 'To speed up approval, you can contact an Admin:',
      'no_admin_phones': 'No admin phone numbers available at the moment',
      'check_status_btn': 'Check Status',
      'no_account': 'Don\'t have an account? ',
      'register_btn': 'Register',
      'first_name': 'First Name',
      'last_name': 'Last Name',
      'age': 'Age',
      'phone': 'Phone Number',
      'select_region': 'Select Region',
      'district': 'District (Residence)',
      'create_password': 'Create Password',
      'i_agree': 'I agree to the',
      'privacy_policy': 'Privacy Policy',
      'new_master_profile': 'New Master Profile',
      'enter_correct_data': 'Enter all data correctly',
      'fill_all_fields': 'Please fill all fields!',
      'password_min_6': 'Password must be at least 6 characters',
      'agree_policy': 'Please agree to the Privacy Policy!',
      'age_min_15': 'You must be at least 15 years old',
      'scanned_msg': 'Scanned:',
      'great': 'Great!',
      'price': 'Price',
      'scanned_times': 'Scanned',
      'times': 'times',
      'close': 'Close',
      'login': 'Login',
      'error': 'Error',
      'send': 'Send',
      'manual_entry': 'Manual entry',
      'enter_qr_number': 'Enter the number under the QR code',
      'cancel': 'Cancel',
      'confirm': 'Confirm',
      'leave_complaint': 'Leave a complaint',
      'submit': 'Submit',
      'verify_code': 'Verify code',
      'enter_6_digit': 'Enter 6-digit code',
      'code_resent': 'Code resent',
      'reset_password': 'Reset password',
      'passwords_mismatch': 'Passwords do not match',
      'registration': 'Registration',
      'application_pending': 'Your application is still pending',
      'no_admin_numbers': 'No admin numbers available yet',
      'check_status': 'Check status',
      'logout_account': 'Log out',
      'no_activity': 'No activity yet',
      'image_uploaded': 'Image uploaded',
      'profile_updated': 'Profile updated',
      'delete_account_confirm': 'Are you sure you want to delete your account? This action cannot be undone.',
      'status': 'Status',
      'status_active': 'Active (New)',
      'status_inactive': 'Used',
      'attention': 'Attention',
      'scanned_by_self': 'You have already scanned this!',
      'scanned_by_other': 'This QR code has already been activated!',
      'send_complaint': 'Send complaint',
      'understood': 'Understood',
      'congratulations': 'Congratulations!',
      'loading': 'Loading...',
      'login_to_add_points': 'Log in to add these points to your account!',
      'complaint_sent': 'Complaint sent',
      'camera_error': 'Could not start camera.\nPlease restart the app.',
      'product_activated': 'Product successfully activated!',
      'for_product_activated': 'successfully activated.',
    }
  };

  static String get(String key) {
    return _translations[localeNotifier.value]?[key] ?? key;
  }
}

extension LocalizationHelper on String {
  String get tr {
    return AppLocalizations.get(this);
  }
}
